version: '3.8'

services:

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "1081:80"
    volumes:
      - "./:/var/www"
      - "./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf"
    links:
      - php

  php:
    restart: unless-stopped
    build: .
    volumes:
      - "./:/var/www"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      APP_ENV: dev
      DATABASE_URL: ${DATABASE_URL}
    user: '1000'
    depends_on:
      - composer

  composer:
    image: composer:latest
    command: install --ignore-platform-reqs --no-scripts
    volumes:
      - .:/app