version: '3.8'

services:

  tindoo_nginx:
    container_name: tindoo_dev_nginx
    image: nginx:1.27
    restart: always
    ports:
      - "1081:80"
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/errors.conf:/etc/nginx/errors.conf:ro
      - ./nginx/html:/usr/share/nginx/html
    links:
      - tindoo_php
    networks:
      - cours_sql

  tindoo_php:
    container_name: tindoo_dev_php
    restart: unless-stopped
    build: .
    volumes:
      - ./:/var/www/html
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      APP_ENV: dev
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "9001:9000"
    networks:
      - cours_sql

  tindoo_mailhog:
    container_name: tindoo_dev_mailhog
    image: mailhog/mailhog
    ports:
      - "1027:1025"
      - "8025:8025"
    networks:
      - cours_sql

networks:
  cours_sql:
    external:
      name: cours_sql