version: '3.8'

services:

  tindoo_nginx:
    container_name: tindoo_nginx
    image: nginx:1.27
    restart: always
    ports:
      - "1081:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    links:
      - tindoo_php
    networks:
      - nginx-proxy

  tindoo_php:
    restart: always
    container_name: tindoo_php
    build: .
    volumes:
      - ./:/var/www/html
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      APP_ENV: ${APP_ENV}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "9000:9000"
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy