version: '3.8'

services:

  nginx:
    image: nginx:1.21
    restart: unless-stopped
    ports:
      - "8081:80"
      - "444:443"
    volumes:
      - ./:/var/www/html
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ../vps-config/certbot/conf:/etc/letsencrypt
    links:
      - tindoo_php
    networks:
      - nginx-proxy

  tindoo_php:
    restart: unless-stopped
    container_name: tindoo_php
    build: .
    volumes:
      - ./:/var/www/html
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      APP_ENV: prod
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "9000:9000"
    user: '1000'
    depends_on:
      - composer

  composer:
    image: composer:latest
    command: install --ignore-platform-reqs --no-scripts
    volumes:
      - .:/app

  node:
    image: node:latest
    volumes:
      - .:/app
    working_dir: /app


networks:
  nginx-proxy:
    external:
      name: nginx-proxy